Repository openshift/monitoring-plugin, pull requests merged in 2023-08, with the labels that each got.

#63 Change i18n namespace to `plugin__monitoring-plugin`
  Dockerfile
  Dockerfile.cypress
  i18next-parser.config.js
  locales/en/plugin__monitoring-plugin.json
  locales/ja/plugin__monitoring-plugin.json
  locales/ja/public.json
  locales/ko/plugin__monitoring-plugin.json
  locales/ko/public.json
  locales/zh/plugin__monitoring-plugin.json
  locales/zh/public.json
  package.json
  src/components/alerting.tsx
  src/components/console/console-shared/alerts/error.tsx
  src/components/dashboards/custom-time-range-modal.tsx
  src/components/dashboards/index.tsx
  src/components/dashboards/table.tsx
  src/components/dashboards/timespan-dropdown.tsx
  src/components/dashboards/useFetchDashboards.ts
  src/components/labels.tsx
  src/components/metrics.tsx
  src/components/poll-interval-dropdown.tsx
  src/components/promql-expression-input.tsx
  src/components/query-browser.tsx
  src/components/silence-form.tsx
  src/components/table-pagination.tsx
  src/components/targets.tsx
  src/i18n.ts
  webpack.config.ts
  yarn.lock
Labels: lgtm, approved

#66 OU-191: Fix width of dashboards tables to use full panel width
  src/components/_monitoring.scss
Labels: lgtm, jira/valid-reference, approved

#67 OU-230: Remove checkboxes from the Silenced By list on alert details page
  src/components/alerting.tsx
Labels: lgtm, jira/valid-reference, approved

#65 OCPBUGS-15323: Use datasource defined in dashboard definition broken by switch to web console monitoring plugin
  src/components/dashboards/index.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#68 OCPBUGS-17650: Fix /monitoring/ redirects
  console-extensions.json
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#69 OCPBUGS-7184: Fix bug where the variable dropdown options were not updated
  src/components/dashboards/index.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug
