Repository openshift/monitoring-plugin, pull requests merged in 2024-09, with the labels that each got.

#176 dates to chart automation
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: needs-ok-to-test, lgtm, approved

#177 incident chart functionality part1
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: needs-ok-to-test, lgtm, approved

#181 remove small chart titles and legend files
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChartLegend.jsx
Labels: needs-ok-to-test

#182 Incidents filters
  package.json
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
  yarn.lock
Labels: needs-ok-to-test

#179 OU-450: Use plugin-backend as default ENTRYPOINT
  Dockerfile.art
  Dockerfile.ci
  Dockerfile.local
Labels: lgtm, jira/valid-reference, approved

#185 severity utils update to show severity changes overtime
  src/components/Incidents/utils.js
Labels: lgtm, approved, ok-to-test

#186 OCPBUGS-41602: Reduce default logging
  README.md
  cmd/plugin-backend.go
  pkg/server.go
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#188 NO-JIRA: Remove Panic on un-parsable log level
  pkg/server.go
Labels: lgtm, jira/valid-reference, approved

#190 add jsdoc for 2 utils funcitons
  src/components/Incidents/utils.js
Labels: needs-ok-to-test

#189 RHINENG-12334: filters for incidents
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#192 incidents-filter-matcher
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: needs-ok-to-test

#195 update incidents filter to allow multiple selected options
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: needs-ok-to-test

#193 OCPBUGS-42053: fix dompurify vulnerable dependency
  web/package.json
  web/tsconfig.json
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#183 OU-499: Migrate `IntervalDropdown`, `TimespanDropdown` to PF5
  web/package.json
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsDetailPage.tsx
  web/src/components/alerting/SilencesUtils.tsx
  web/src/components/dashboards/index.tsx
  web/src/components/dashboards/timespan-dropdown.tsx
  web/src/components/kebab-dropdown.tsx
  web/src/components/metrics.tsx
  web/src/components/poll-interval-dropdown.tsx
  web/src/components/query-browser.tsx
  web/src/components/silence-form.tsx
  web/src/components/table-pagination.tsx
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved

#194 OCPBUGS-41560: fix path-to-regexp dependency
  web/package.json
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#184 OU-259: Remove `public~` i18n translation references
  web/console-extensions.json
  web/i18n-scripts/build-i18n.sh
  web/i18n-scripts/common.js
  web/i18n-scripts/lexers.js
  web/i18n-scripts/set-english-defaults.js
  web/locales/en/plugin__monitoring-plugin.json
  web/package.json
  web/src/components/console/console-shared/alerts/error.tsx
  web/src/components/console/graphs/graph-empty.tsx
  web/src/components/console/models/index.ts
  web/src/components/console/utils/button-bar.jsx
  web/src/components/console/utils/status-box.tsx
  web/src/i18n.ts
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved
