Repository openshift/monitoring-plugin, pull requests merged in 2024-11, with the labels that each got.

#218 OCPBUGS-43242: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.15
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#219 OCPBUGS-43243: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.14
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#243 OCPBUGS-44137: upgrade dompurify dependency
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#245 NO-JIRA: Update readme with feature info
  README.md
Labels: lgtm, jira/valid-reference, approved

#246 COO-519: make config path explicit in konflux image
  Dockerfile.konflux
Labels: lgtm, jira/valid-reference, approved

#242 RHINENG-12634:process incidents typescript conversion
  web/src/components/Incidents/processIncidents.js
  web/src/components/Incidents/processIncidents.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#250 RHINENG-10906: Filters to url params
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/utils.js
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#251 NO-JIRA: Refactor usestates to redux
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#256 NO-JIRA: incidents feature squashed into 1 commit
  config/incidents.patch.json
  web/console-extensions.json
  web/src/actions/observe.ts
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/components/Incidents/api.js
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/processAlerts.js
  web/src/components/Incidents/processIncidents.ts
  web/src/components/Incidents/utils.js
  web/src/components/alerting.tsx
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#252 OU-257: Migrate Developer View > Observe > Silences Tab from openshift/console to openshift/monitoring-plugin
  web/console-extensions.json
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsDetailPage.tsx
  web/src/components/alerting/SilencesPage.tsx
  web/src/components/silence-form.tsx
  web/src/components/utils.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved

#257 NO-JIRA: remove incidents from default extensions
  web/console-extensions.json
Labels: lgtm, jira/valid-reference, approved

#259 NO-JIRA: Update readme and deployment scripts
  Dockerfile.mcp
  Makefile
  README.md
  pkg/server.go
  scripts/build-image.sh
  scripts/deploy-acm.sh
Labels: lgtm, jira/valid-reference, approved

#258 OCPBUGS-44391: fix cross-spawn vulnerable dependency
  web/package-lock.json
  web/package.json
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#260 OCPBUGS-44447: Don't set property on undefined variable
  web/src/reducers/observe.ts
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug

#262 OU-584: Fix issues preventing the incidents tab from showing
  config/incidents.patch.json
  web/console-extensions.json
  web/package.json
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/alerting.tsx
  web/src/components/hooks/useFeatures.ts
Labels: lgtm, jira/valid-reference, approved

#263 NO-JIRA: updated api request to remove prom tenancy issue
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/components/Incidents/api.js
Labels: needs-ok-to-test, lgtm, jira/valid-reference, approved

#261 OU-589: Update helm chart to support incidents
  charts/openshift-console-plugin/templates/_helpers.tpl
  charts/openshift-console-plugin/templates/consoleplugin.yaml
  charts/openshift-console-plugin/templates/deployment.yaml
  charts/openshift-console-plugin/templates/patcher-clusterrole.yaml
  charts/openshift-console-plugin/templates/patcher-clusterrolebinding.yaml
  charts/openshift-console-plugin/templates/patcher-consoles-job.yaml
  charts/openshift-console-plugin/templates/patcher-serviceaccount.yaml
  charts/openshift-console-plugin/templates/service.yaml
  charts/openshift-console-plugin/values.yaml
  scripts/deploy-acm.sh
Labels: lgtm, jira/valid-reference, approved

#265 NO-JIRA: only 1 alert in table fix
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/processIncidents.ts
Labels: lgtm, jira/valid-reference, approved

#268 OU-590: upgrade dynamic plugin sdk webpack to load correct patternfly dependency
  Dockerfile
  Dockerfile.art
  Dockerfile.dev
  Dockerfile.konflux
  Dockerfile.mcp
  config/incidents.patch.json
  scripts/update-plugin-name.sh
  web/package-lock.json
  web/package.json
  web/webpack.config.ts
Labels: lgtm, jira/valid-reference, approved

#269 NO-JIRA: Remove extra copy that fails
  Dockerfile.mcp
Labels: lgtm, jira/valid-reference, approved

#270 RHINENG-14524: incidents charts update cursor and
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#271 OCPBUGS-44394: remove unused package and upgrade vulnerable dependency
  web/package.json
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug

#274 RHINENG-14523: Fix expanded row won't render without rule details + firing logic update
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/components/Incidents/api.js
  web/src/components/Incidents/processAlerts.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#276 NO-JIRA: Fix feature flagged DX
  Makefile
  README.md
  cmd/plugin-backend.go
  config/dev-config.patch.json
  pkg/plugin_handler.go
  pkg/server.go
  scripts/start-console.sh
Labels: lgtm, jira/valid-reference, approved

#275 NO-JIRA: fix incidents filter width
  web/src/components/Incidents/IncidentsPage.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test
