Repository openshift/monitoring-plugin, pull requests merged in 2024-12, with the labels that each got.

#272 OCPBUGS-44395: remove unused package and upgrade vulnerable dependency
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#264 OCPBUGS-35726: fix cert/key file reload
  cmd/plugin-backend.go
  pkg/server.go
  pkg/server_test.go
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug

#277 OCPBUGS-44393: Manual cherry pick cross spawn 4.15
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#279 RHINENG-14677: fix filters for incidents
  web/src/components/Incidents/processIncidents.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#278 [release-4.14] OCPBUGS-44392: fix cross-spawn vulnerable dependency
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#280 RHINENG-14585: Remove pending alerts from processing and add another value to the unique key
  web/src/components/Incidents/processAlerts.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#283 RHINENG-14523: (fix) update expanded details
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/incidents-styles.css
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#281 NO-JIRA: multiple components in tooltip for incidents
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/processIncidents.ts
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#285 RHINENG-14555: Update for the filters and default state for the filters
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/processIncidents.ts
  web/src/components/Incidents/utils.js
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#282 OU-499: Port CONSOLE-4124, ODC-7655, CONSOLE-4127 to dynamic plugin
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/_monitoring.scss
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/alerting/SilencesDetailPage.tsx
  web/src/components/console/utils/single-typeahead-dropdown.tsx
  web/src/components/dashboards/index.tsx
  web/src/components/kebab-dropdown.tsx
  web/src/components/metrics.tsx
  web/src/components/query-browser.tsx
  web/src/components/silence-form.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved

#266 OU-432: Merge Perses dashboards with current dashboards list
  scripts/start-console.sh
  web/src/components/cancellable-fetch.ts
  web/src/components/dashboards/index.tsx
  web/src/components/dashboards/perses-client.ts
  web/src/components/dashboards/usePerses.ts
Labels: lgtm, jira/valid-reference, approved

#286 OU-561: Use AlertsRulesDetailPage from `monitoring-plugin`
  web/console-extensions.json
  web/locales/en/plugin__monitoring-plugin.json
  web/src/components/alerting.tsx
  web/src/components/alerting/README.md
Labels: lgtm, jira/valid-reference, approved, qe-approved

#292 OCPBUGS-45801: Allow editing the until field on the silence edit page
  web/src/components/silence-form.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug

#295 OCPBUGS-45174: Fix bounds on bar chart
  web/src/components/console/graphs/bar.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug

#290 NO-JIRA: Run webpack with a different port
  web/webpack.config.ts
Labels: lgtm, jira/valid-reference, approved

#300 OCPBUGS-46083: fix button spacing on silence form
  web/src/components/silence-form.tsx
Labels: lgtm, jira/severity-low, jira/valid-reference, approved, jira/valid-bug

#288 OCPBUGS-45896: Fix admin console alert detail graph
  web/src/components/query-browser.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug, qe-approved

#296 NO-JIRA: Remove duplicate parameter
  web/src/components/alerting/AlertUtils.tsx
  web/src/components/dashboards/graph.tsx
  web/src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved

#303 OU-588: Move Incidents Tab to Alerting Page
  config/incidents.patch.json
  scripts/start-console.sh
  web/src/components/alerting.tsx
  web/src/components/hooks/useFeatures.ts
  web/src/components/hooks/usePerspective.tsx
Labels: lgtm, jira/valid-reference, approved
