Repository openshift/monitoring-plugin, pull requests merged in 2024-10, with the labels that each got.

#198 feat(RHINENG-10902): Incidents table implementation
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/IncidentsTableRow.jsx
  src/components/Incidents/api.js
  src/components/Incidents/consts.js
  src/components/Incidents/utils.js
Labels: needs-ok-to-test

#199 OCPBUGS-41206: use monospace for tables values for better identification
  web/locales/en/plugin__monitoring-plugin.json
  web/src/components/_monitoring.scss
  web/src/components/metrics.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#203 NO-JIRA: Update log-level docs in monitoring-plugin
  README.md
Labels: lgtm, jira/valid-reference, approved

#200 OU-550: Use npm instead of yarn
  Dockerfile
  Dockerfile.art
  Dockerfile.ci
  Dockerfile.cypress
  Dockerfile.local
  Dockerfile.test
  Makefile
  README.md
  web/.husky/pre-commit
  web/package-lock.json
  web/package.json
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved

#167 OU-259: Migrate Dev > Observe > Dashboard Page
  web/console-extensions.json
  web/src/components/alerting.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved

#205 RHINENG-12637: add onclick to incidents chart
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsDetailsRowTable.jsx
  src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/api.js
  src/components/Incidents/processAlerts.js
  src/components/Incidents/processIncidents.js
  src/components/Incidents/utils.js
Labels: needs-ok-to-test, lgtm, jira/valid-reference, approved

#209 OU-406: add konflux dockerfile
  Dockerfile.konflux
Labels: lgtm, jira/valid-reference, approved

#215 RHINENG-10537: update chart generating logic for rows
  src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#223 empty states for chart and table
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsTable.jsx
Labels: lgtm, approved, ok-to-test

#224 fixed links in expanded details table
  src/components/Incidents/IncidentsDetailsRowTable.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/IncidentsTable.jsx
Labels: needs-ok-to-test

#221 OCPBUGS-42851: Refresh interval button on "Observe -> Metrics" page failed to load for admin/developer console
  web/src/components/SimpleSelect.tsx
  web/src/components/dropdown-poll-interval.tsx
  web/src/components/metrics.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug, qe-approved

#228 RHINENG-10904: Kebab actions for expanded details
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/console/graphs/bar.tsx
  web/src/components/query-browser-theme.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#216 OCPBUGS-43238: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.17
  web/package.json
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#231 Incidents chart fixed double tooltip bug
  web/src/components/Incidents/utils.js
Labels: needs-ok-to-test

#229 OU-506: prefetch dependencies for konflux pipelines
  .tekton/monitoring-console-plugin-0-3-pull-request.yaml
  .tekton/monitoring-console-plugin-0-3-push.yaml
  web/package-lock.json
  web/package.json
Labels: lgtm, jira/valid-reference, approved

#217 OCPBUGS-43239: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.16
  package.json
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved

#232 COO-493: Fix alerts page kebab dropdown
  web/src/components/alerting/AlertsPage.tsx
Labels: lgtm, jira/valid-reference, approved

#233 RHINENG-10907: Filter to toolbar refactor
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/utils.js
Labels: needs-ok-to-test, lgtm, jira/valid-reference, approved

#235 Made fetch for incidents nav DRYer
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/api.js
Labels: lgtm, approved, ok-to-test

#241 Incidents expanded details: fixed broken links bug
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
Labels: needs-ok-to-test

#240 Incidents: Add withFallback to incidents page
  web/src/components/alerting.tsx
Labels: needs-ok-to-test

#237 OCPBUGS-42845: Fix Dashboard/Metrics Drop-Downs
  web/src/components/SimpleSelect.tsx
  web/src/components/dashboards/index.tsx
  web/src/components/dashboards/timespan-dropdown.tsx
  web/src/components/dropdown-poll-interval.tsx
  web/src/components/metrics.tsx
  web/src/components/poll-interval-dropdown.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug, qe-approved
