Repository openshift/monitoring-plugin, pull requests merged in 2024-07, with the labels that each got.

#125 OU-251: Migrate Developer Perspective Alert List to Monitoring Plugin
  console-extensions.json
  src/actions/observe.ts
  src/components/alerting.tsx
  src/components/alerting/AlertUtils.tsx
  src/components/alerting/AlertsPage.tsx
  src/components/alerting/README.md
  src/components/console/console-shared/hooks/useActiveNamespace.ts
  src/components/dashboards/custom-time-range-modal.tsx
  src/components/dashboards/graph.tsx
  src/components/dashboards/index.tsx
  src/components/dashboards/monitoring-dashboard-utils.ts
  src/components/dashboards/timespan-dropdown.tsx
  src/components/dashboards/types.ts
  src/components/fetch-alerts.tsx
  src/components/hooks/usePerspective.tsx
  src/components/silence-form.tsx
  src/components/utils.ts
Labels: lgtm, jira/valid-reference, approved

#129 OU-439: Add the predefined queries list to the admin metrics
  locales/en/plugin__monitoring-plugin.json
  src/components/_monitoring.scss
  src/components/metrics.tsx
Labels: lgtm, jira/valid-reference, approved

#132 OU-251: Prevent rule labels from being added to alert labels for dev console
  src/components/alerting.tsx
  src/components/utils.ts
Labels: lgtm, jira/valid-reference, approved

#134 OCPBUGS-36970: Use the non-tenancy URL in the Admin perspective
  src/components/alerting.tsx
Labels: lgtm, jira/severity-critical, jira/valid-reference, approved, jira/valid-bug, qe-approved

#127 OU-238: Export CSV
  src/components/dashboards/graph.tsx
  src/components/dashboards/index.tsx
  src/components/query-browser.tsx
  start-console.sh
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#131 OU-248: Add Alerts Detail Page
  console-extensions.json
  locales/en/plugin__monitoring-plugin.json
  src/components/alerting.tsx
  src/components/alerting/AlertUtils.tsx
  src/components/alerting/AlertsDetailPage.tsx
  src/components/alerting/AlertsPage.tsx
  src/components/alerting/README.md
  src/components/alerting/SilencesUtils.tsx
  src/components/hooks/useRulesAlertsPoller.ts
  src/components/hooks/useSilencesPoller.ts
  src/components/hooks/useURLPoll.ts
  src/components/utils.ts
Labels: lgtm, jira/valid-reference, approved

#135 NO-JIRA: Fix docker local and log query browser error
  Dockerfile.local
  src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved
