Repository openshift/monitoring-plugin, pull requests merged in 2024-08, with the labels that each got.

#138 OU-258: Dev console: Use Metrics page from monitoring-plugin
  console-extensions.json
  src/components/alerting.tsx
  src/components/metrics.tsx
  src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved

#142 NO-JIRA: Fix art image cachito path for yarn lock
  Dockerfile.art
Labels: lgtm, jira/valid-reference, approved

#141 NO-JIRA: Migrating chart to patternfly
  package.json
  src/components/Incidents/AlertsChart/AlertsChart.css
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/AlertsChart/IncidentsChartLegend.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.css
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  yarn.lock
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#144 NO-JIRA: fix cachito target folder
  Dockerfile.art
Labels: lgtm, jira/valid-reference, approved

#146 NO-JIRA: fix cachito pem file location
  Dockerfile.art
Labels: lgtm, jira/valid-reference, approved

#149 NO-JIRA: fix command chain for art image
  Dockerfile.art
Labels: lgtm, jira/valid-reference, approved

#151 NO-JIRA: fix cachito web folder
  Dockerfile.art
Labels: lgtm, jira/valid-reference, approved

#154 NO-JIRA: Use DNF and go based image in Dockerfile
  Dockerfile
Labels: lgtm, jira/valid-reference, approved

#133 OU-431: Export CSV for Alert Tables
  web/package.json
  web/src/components/alerting/AlertsPage.tsx
  web/yarn.lock
Labels: lgtm, jira/valid-reference, approved, qe-approved

#148 refactored fetch connected it to data processing
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/_monitoring.scss
Labels: needs-ok-to-test

#157 NO-JIRA: add FIPS compliant flags and env vars
  Dockerfile
  Dockerfile.art
  Makefile
Labels: lgtm, jira/valid-reference, approved

#158 updated patternfly react charts to solve bugs
  package.json
  src/components/console/graphs/bar.tsx
  src/components/query-browser-theme.ts
  yarn.lock
Labels: lgtm, approved, ok-to-test

#160 NO-JIRA: downgrade to go 1.21 to be able to use cachito
  Dockerfile.art
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, approved

#162 NO-JIRA: upgrade to go 1.22 fixing the z version
  go.mod
Labels: lgtm, jira/valid-reference, approved

#164 NO-JIRA: Update query-browser to not use setState
  web/src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved

#165 OCPBUGS-36921: Use resource label when showing empty alert list pages
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/console/utils/status-box.tsx
Labels: lgtm, jira/severity-low, jira/valid-reference, approved, jira/valid-bug

#168 Improved fetch and data preparation for charts
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: lgtm, approved, ok-to-test

#169 OU-446: Add comment reminding to add FIPS CI checks
  Dockerfile
  Dockerfile.art
  Dockerfile.ci
  Dockerfile.local
Labels: jira/valid-reference, approved

#170 data from the api mapped onto chart
  src/components/Incidents/AlertsChart/AlertsChart.jsx
  src/components/Incidents/IncidentsPage.jsx
  src/components/Incidents/utils.js
Labels: ok-to-test

#172 OCPBUGS-36921: Fix empty filter state on alerting and targets
  web/locales/en/plugin__monitoring-plugin.json
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/targets.tsx
Labels: lgtm, jira/severity-low, jira/valid-reference, approved, jira/valid-bug

#171 NO-JIRA: Add `make install` command to install frontend and backend dependencies
  Makefile
  README.md
Labels: lgtm, jira/valid-reference, approved

#173 OU-259: Update console-extension to use translations in plugin__monitoring-plugin
  web/console-extensions.json
Labels: lgtm, jira/valid-reference, approved

#174 NO-JIRA: Fix default paths for go-server
  cmd/plugin-backend.go
Labels: lgtm, jira/valid-reference, approved

#175 Revert "OU-259: Update console-extension to use translations in plugin__monitoring-plugin"
  web/console-extensions.json
Labels: lgtm, jira/valid-reference, approved
