Repository openshift/monitoring-plugin, pull requests merged in 2025-05, with the labels that each got.

#404 OU-745: Check for CSRF change on each fetch cycle
  web/src/components/dashboards/perses/PersesWrapper.tsx
  web/src/components/dashboards/perses/datasource-api.ts
  web/src/components/dashboards/perses/hooks/useCookieWatcher.ts
  web/src/components/dashboards/perses/perses-client.ts
  web/src/components/dashboards/perses/perses/datasource-api.ts
  web/src/components/dashboards/perses/variable-dropdowns.tsx
  web/src/components/proxied-fetch.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#401 RHINENG-10537: fixed broken delete chip group for incidents filters
  web/src/components/Incidents/IncidentsPage.jsx
Labels: needs-ok-to-test, lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#403 RHINENG-17675: feat: add group id to url params
  web/src/actions/observe.ts
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/utils.ts
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#402 OU-774: bound table scroll and column alignment
  web/src/components/MetricsPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#410 OU-794: fix: update monitoring and virtualization routes to avoid overriding console routes
  config/acm-alerting.patch.json
  web/console-extensions.json
  web/package.json
  web/src/components/alerting/AlertRulesPage.tsx
  web/src/components/alerting/AlertingPage.tsx
  web/src/components/alerting/SilencesPage.tsx
  web/src/components/dashboards/legacy/legacy-dashboard-page.tsx
  web/src/components/dashboards/perses/dashboard-page.tsx
  web/src/components/dashboards/shared/useIsPerses.ts
  web/src/components/prometheus-redirect-page.tsx
  web/src/components/router.tsx
  web/src/e2e-tests-app.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#413 OU-712: fix: add missing alertname field to silence alert
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#414 OCPBUGS-56095: "Negative matcher" is checked by default on Create silence page
  web/src/components/alerting/SilenceForm.tsx
Labels: lgtm, jira/severity-low, jira/valid-reference, approved, jira/valid-bug, qe-approved, ux-approved

#416 NO-JIRA: Fix missing commits
  Dockerfile.dev
  Dockerfile.mcp
  web/src/components/alerting/AlertsPage.tsx
Labels: jira/valid-reference, approved

#419 OU-829: fix ACM filtering and 'Export as CSV' link
  web/src/components/alerting/AlertList/DownloadCSVButton.tsx
  web/src/components/alerting/AlertsPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved
