Repository openshift/monitoring-plugin, pull requests merged in 2025-09, with the labels that each got.

#510 NO-JIRA: Test config interactive setup
  web/cypress/README.md
  web/cypress/configure-env.sh
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#519 OU-897: automation OU-721 and hygiene of existing scripts
  web/cypress/e2e/coo/01.coo_bvt.cy.ts
  web/cypress/e2e/monitoring/01.bvt_monitoring.cy.ts
  web/cypress/e2e/monitoring/regression/01.reg_alerts.cy.ts
  web/cypress/e2e/monitoring/regression/02.reg_metrics.cy.ts
  web/cypress/e2e/monitoring/regression/03.reg_legacy_dashboards.cy.ts
  web/cypress/fixtures/coo/perses-dashboard-sample.yaml
  web/cypress/fixtures/coo/prometheus-overview-variables.yaml
  web/cypress/fixtures/coo/thanos-compact-overview-1var.yaml
  web/cypress/fixtures/monitoring/alert.ts
  web/cypress/fixtures/monitoring/constants.ts
  web/cypress/support/commands/operator-commands.ts
  web/cypress/views/alerting-rule-details-page.ts
  web/cypress/views/common.ts
  web/cypress/views/metrics.ts
  web/src/components/data-test.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#520 RHINENG-20424: Incident ID filter for the Incidents Page
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx
  web/src/components/Incidents/IncidentsPage.tsx
  web/src/components/Incidents/ToolbarItemFilter.tsx
  web/src/components/Incidents/incidents-styles.css
  web/src/components/Incidents/model.ts
  web/src/components/Incidents/utils.ts
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#529 OU-783: Fit the alerts timeline to the actual data timespan
  web/src/components/Incidents/AlertsChart/AlertsChart.tsx
  web/src/components/Incidents/IncidentsPage.tsx
  web/src/components/Incidents/utils.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#527 RHINENG-20424: fix clear filter bug with incident selected
  web/src/components/Incidents/IncidentsPage.tsx
  web/src/components/Incidents/ToolbarItemFilter.tsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#532 NO-JIRA: automation - fix monitoring-plugin injection
  web/cypress/fixtures/cmo/update-monitoring-plugin-image.sh
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#530 RHINENG-20667: silenced alerts for chart and table
  web/src/components/Incidents/AlertsChart/AlertsChart.tsx
  web/src/components/Incidents/IncidentAlertStateIcon.tsx
  web/src/components/Incidents/IncidentsDetailsRowTable.tsx
  web/src/components/Incidents/IncidentsPage.tsx
  web/src/components/Incidents/IncidentsTable.tsx
  web/src/components/Incidents/model.ts
  web/src/components/Incidents/processAlerts.ts
  web/src/components/Incidents/utils.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#533 NO-JIRA: set rules as silenced if all alerts are silenced
  web/src/components/alerting/AlertRulesPage.tsx
  web/src/components/alerting/AlertUtils.tsx
  web/src/components/utils.ts
  web/src/store/reducers.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#521 OBSINTA-798: Cypress Incident Tests – Query Mocking
  .cursor/commands/fixture-schema-reference.md
  .cursor/commands/generate-incident-fixture.md
  .cursor/commands/validate-incident-fixtures.md
  web/cypress.config.ts
  web/cypress/README.md
  web/cypress/configure-env.sh
  web/cypress/e2e/incidents/01.incidents.cy.ts
  web/cypress/e2e/incidents/02.incidents-mocking-example.cy.ts
  web/cypress/fixtures/export.sh
  web/cypress/fixtures/incident-scenarios/0-healthy-cluster.yaml
  web/cypress/fixtures/incident-scenarios/1-single-incident-firing-critical-and-warning-alerts.yaml
  web/cypress/fixtures/incident-scenarios/2-multi-incidents-multi-alerts-resolved-and-firing.yaml
  web/cypress/fixtures/incident-scenarios/3-multi-severity-overlapping-incidents.yaml
  web/cypress/fixtures/incident-scenarios/4-single-incident-warning-alerts-only.yaml
  web/cypress/fixtures/incident-scenarios/5-escalating-severity-incident.yaml
  web/cypress/support/incidents_prometheus_query_mocks/README.md
  web/cypress/support/incidents_prometheus_query_mocks/index.ts
  web/cypress/support/incidents_prometheus_query_mocks/mock-generators.ts
  web/cypress/support/incidents_prometheus_query_mocks/prometheus-mocks.ts
  web/cypress/support/incidents_prometheus_query_mocks/schema/fixture-converter.ts
  web/cypress/support/incidents_prometheus_query_mocks/schema/fixture-schema.json
  web/cypress/support/incidents_prometheus_query_mocks/schema/schema-validator.ts
  web/cypress/support/incidents_prometheus_query_mocks/schema/validate-fixtures.ts
  web/cypress/support/incidents_prometheus_query_mocks/schema/yaml-fixture-snippets.json
  web/cypress/support/incidents_prometheus_query_mocks/types.ts
  web/cypress/support/incidents_prometheus_query_mocks/utils.ts
  web/cypress/support/index.ts
  web/package-lock.json
  web/package.json
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#531 RHINENG-20701: fix utc timestamps in chart tooltips
  web/src/components/Incidents/AlertsChart/AlertsChart.tsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx
  web/src/components/Incidents/utils.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#534 OBSINTA-789: Update layout and labels
  web/src/components/Incidents/AlertsChart/AlertsChart.tsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx
  web/src/components/Incidents/IncidentsPage.tsx
  web/src/components/Incidents/IncidentsTable.tsx
  web/src/components/Incidents/incidents-styles.css
  web/src/components/Incidents/utils.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#514 OBSINTA-463: Rename the cluster health metrics
  web/src/components/Incidents/IncidentsPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#538 OCPBUGS-61891: feat: add alerting rules tab to dev console
  web/console-extensions.json
  web/src/components/alerting.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, qe-approved, ux-approved

#539 OU-833: fix 2 bugs for incidents page
  web/src/components/Incidents/AlertsChart/AlertsChart.tsx
  web/src/components/Incidents/ToolbarItemFilter.tsx
  web/src/components/Incidents/model.ts
  web/src/components/Incidents/utils.ts
  web/src/store/store.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#544 NO-JIRA: Login validation for all session flows
  web/cypress/support/commands/auth-commands.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#546 RHINENG-20863: improved fetching logic for incidents
  web/src/components/Incidents/IncidentsPage.tsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#552 OU-1005: Manual cherry pick upgrade Perses plugins
  web/package-lock.json
  web/package.json
  web/src/components/console/utils/single-typeahead-dropdown.tsx
  web/src/components/dashboards/perses/PersesWrapper.tsx
  web/src/components/dashboards/perses/persesPluginsLoader.tsx
  web/src/components/kebab-dropdown.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#543 OU-989: Kubevirt with fixes after namespace level and session handler
  web/cypress/README.md
  web/cypress/configure-env.sh
  web/cypress/e2e/coo/01.coo_ivt.cy.ts
  web/cypress/e2e/monitoring/01.bvt_monitoring.cy.ts
  web/cypress/e2e/monitoring/regression/01.reg_alerts.cy.ts
  web/cypress/e2e/monitoring/regression/02.reg_metrics.cy.ts
  web/cypress/fixtures/cmo/disable-monitoring.yaml
  web/cypress/fixtures/cmo/enable-monitoring.yaml
  web/cypress/fixtures/cmo/reenable-monitoring.sh
  web/cypress/fixtures/cmo/update-monitoring-plugin-image.sh
  web/cypress/fixtures/coo/update-mcp-image.sh
  web/cypress/fixtures/virtualization/hyperconverged.yaml
  web/cypress/fixtures/virtualization/virtualization_stage.sh
  web/cypress/support/commands/auth-commands.ts
  web/cypress/support/commands/operator-commands.ts
  web/cypress/support/commands/utility-commands.ts
  web/cypress/support/commands/virtualization-commands.ts
  web/cypress/support/index.ts
  web/cypress/views/alerting-rule-list-page.ts
  web/cypress/views/common.ts
  web/cypress/views/details-page.ts
  web/cypress/views/nav.ts
  web/cypress/views/tour.ts
  web/package.json
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#545 OBSINTA-795: Data Test Selectors for Incidents Page
  web/cypress/e2e/incidents/00.coo_incidents_e2e.cy.ts
  web/cypress/e2e/incidents/01.incidents.cy.ts
  web/cypress/e2e/incidents/02.incidents-mocking-example.cy.ts
  web/cypress/fixtures/incident-scenarios/6-multi-incident-target-alert-scenario.yaml
  web/cypress/support/incidents_prometheus_query_mocks/mock-generators.ts
  web/cypress/support/incidents_prometheus_query_mocks/prometheus-mocks.ts
  web/cypress/support/incidents_prometheus_query_mocks/utils.ts
  web/cypress/views/incidents-page.ts
  web/src/components/Incidents/AlertsChart/AlertsChart.tsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx
  web/src/components/Incidents/IncidentsDetailsRowTable.tsx
  web/src/components/Incidents/IncidentsPage.tsx
  web/src/components/Incidents/IncidentsTable.tsx
  web/src/components/Incidents/ToolbarItemFilter.tsx
  web/src/components/data-test.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#559 OU-1011: REVERT add a 5 minute to the first alert timestamp
  web/src/components/Incidents/processAlerts.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#558 NO-JIRA: Update .gitignore (Cypress specific)
  .gitignore
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#562 COO-1133: Upgrade perses plugins coo 0.4
  web/package-lock.json
  web/package.json
  web/src/components/dashboards/perses/PersesWrapper.tsx
  web/src/components/dashboards/perses/persesPluginsLoader.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#561 COO-1134: fix: update vulnerable dependencies
  web/package-lock.json
  web/package.json
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#563 COO-1134: [release-coo-0.5] fix: update vulnerable dependencies
  web/package-lock.json
  web/package.json
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved
