Repository openshift/monitoring-plugin, pull requests merged in 2025-01, with the labels that each got.

#311 RHINENG-15115: update hideshow graph button
  web/src/components/Incidents/IncidentsPage.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#310 RHINENG-15114: incidents page fixed date style inconsistency
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#312 Revert "OU-588: Move Incidents Tab to Alerting Page "
  config/incidents.patch.json
  scripts/start-console.sh
  web/src/components/alerting.tsx
  web/src/components/hooks/useFeatures.ts
  web/src/components/hooks/usePerspective.tsx
Labels: lgtm, jira/valid-reference, approved

#314 OCPBUGS-48142: Fix Dev Perspective Alert URL namespace
  web/src/components/alerting/SilencesDetailPage.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug, qe-approved

#317 OU-630: Add Needed Virtualization Perspective Changes
  README.md
  config/clear-extensions.patch.json
  config/dev-config.patch.json
  web/console-extensions.json
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsDetailPage.tsx
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/alerting/SilencesDetailPage.tsx
  web/src/components/alerting/SilencesPage.tsx
  web/src/components/dashboards/custom-time-range-modal.tsx
  web/src/components/dashboards/graph.tsx
  web/src/components/dashboards/index.tsx
  web/src/components/dashboards/timespan-dropdown.tsx
  web/src/components/hooks/usePerspective.tsx
  web/src/components/metrics.tsx
  web/src/components/query-browser.tsx
  web/src/components/silence-form.tsx
  web/src/components/targets.tsx
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved

#318 [release-4.18] OU-633: Add Needed Virtualization Changed
  README.md
  config/clear-extensions.patch.json
  web/console-extensions.json
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsDetailPage.tsx
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/alerting/SilencesDetailPage.tsx
  web/src/components/alerting/SilencesPage.tsx
  web/src/components/dashboards/custom-time-range-modal.tsx
  web/src/components/dashboards/graph.tsx
  web/src/components/dashboards/index.tsx
  web/src/components/dashboards/timespan-dropdown.tsx
  web/src/components/hooks/usePerspective.tsx
  web/src/components/metrics.tsx
  web/src/components/query-browser.tsx
  web/src/components/silence-form.tsx
  web/src/components/targets.tsx
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved

#316 RHINENG-15190: fix gap in incident charts
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#321 NO-JIRA: revert reset all filters button
  web/src/components/Incidents/IncidentsPage.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#322 RHINENG-15362: Sort the bars in the charts based on their first timestamp
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/processAlerts.js
  web/src/components/Incidents/processIncidents.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#304 OU-433: Split the Dashboard Page between perses and legacy
  cmd/plugin-backend.go
  config/perses-dashboards.patch.json
  pkg/server.go
  scripts/start-console.sh
  web/package-lock.json
  web/package.json
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/alerting.tsx
  web/src/components/console/graphs/helpers.ts
  web/src/components/console/models/index.ts
  web/src/components/console/utils/single-typeahead-dropdown.tsx
  web/src/components/dashboards/dashboard-page.tsx
  web/src/components/dashboards/index.tsx
  web/src/components/dashboards/legacy/bar-chart.tsx
  web/src/components/dashboards/legacy/graph.tsx
  web/src/components/dashboards/legacy/legacy-dashboard.tsx
  web/src/components/dashboards/legacy/single-stat.tsx
  web/src/components/dashboards/legacy/table.tsx
  web/src/components/dashboards/legacy/types.ts
  web/src/components/dashboards/legacy/useLegacyDashboards.ts
  web/src/components/dashboards/perses-client.ts
  web/src/components/dashboards/perses/perses-client.ts
  web/src/components/dashboards/perses/perses-dashboards.tsx
  web/src/components/dashboards/perses/project/ProjectBar.tsx
  web/src/components/dashboards/perses/project/ProjectDropdown.scss
  web/src/components/dashboards/perses/project/ProjectDropdown.tsx
  web/src/components/dashboards/perses/project/ProjectMenuToggle.tsx
  web/src/components/dashboards/perses/project/useActiveProject.tsx
  web/src/components/dashboards/perses/project/utils.ts
  web/src/components/dashboards/perses/usePerses.ts
  web/src/components/dashboards/shared/custom-time-range-modal.tsx
  web/src/components/dashboards/shared/dashboard-dropdown.tsx
  web/src/components/dashboards/shared/dashboard-skeleton.tsx
  web/src/components/dashboards/shared/time-dropdowns.tsx
  web/src/components/dashboards/shared/useDashboardsData.ts
  web/src/components/dashboards/shared/utils.ts
  web/src/components/dashboards/shared/variable-dropdowns.tsx
  web/src/components/dashboards/usePerses.ts
  web/src/components/hooks/useFeatures.ts
  web/src/components/hooks/usePerspective.tsx
  web/src/components/hooks/useQueryParams.ts
  web/src/components/proxied-fetch.ts
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved

#319 RHINENG-15284: Sync alerts chart and incidents table with days filter
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/IncidentsTable.jsx
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#323 RHINENG-15501: Improve incidents filter logic and sync
  web/src/actions/observe.ts
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/processIncidents.ts
  web/src/components/Incidents/utils.js
  web/src/reducers/observe.ts
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#324 NO-JIRA: fixed function for incident chart colors
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#326 NO-JIRA: Don't attempt to access potentially undefined variable
  web/src/components/dashboards/perses/project/ProjectDropdown.tsx
Labels: lgtm, jira/valid-reference, approved

#325 OU-645: Fix virtualization perspective routes and routing
  web/src/components/alerting.tsx
  web/src/components/hooks/usePerspective.tsx
Labels: lgtm, jira/valid-reference, approved

#329 RHINENG-15501: hotfix because filter requirement were updated
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#331 RHINENG-15582: Incidents dark theme support
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#333 RHINENG-15501: Fixing incidents filter issues with severeties and long standing
  web/src/components/Incidents/processIncidents.ts
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#334 RHINENG-15594: fix tooltip in row details
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/processAlerts.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#332 OU-649: fix net/http vulnerable dependency
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, approved

#336 NO-JIRA: Incidents page small fixes
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#339 OU-649: fix net/http vulnerable dependency
  go.mod
  go.sum
Labels: lgtm, jira/valid-reference, approved

#341 RHINENG-10537: fix incidents page loading state issue
  web/src/components/Incidents/IncidentsPage.jsx
  web/src/components/Incidents/consts.js
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test

#340 RHINENG-10537:Voronoi container review branch
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
  web/src/components/Incidents/utils.js
Labels: lgtm, jira/valid-reference, approved, ok-to-test
