Repository openshift/monitoring-plugin, pull requests merged in 2025-08, with the labels that each got.

#485 OU-944: automation refactoring
  web/cypress.config.ts
  web/cypress/e2e/01.bvt_monitoring.cy.ts
  web/cypress/e2e/02.coo_bvt.cy.ts
  web/cypress/e2e/regression/01.reg_alerts.cy.ts
  web/cypress/support/commands.ts
  web/cypress/support/selectors.ts
  web/cypress/views/alerting-rule-list-page.ts
  web/cypress/views/common.ts
  web/cypress/views/details-page.ts
  web/cypress/views/list-page.ts
  web/cypress/views/nav.ts
  web/cypress/views/overview-page.ts
  web/cypress/views/pages.ts
  web/cypress/views/silence-alert-page.ts
  web/cypress/views/silence-details-page.ts
  web/cypress/views/silences-list-page.ts
  web/cypress/views/utils.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#486 NO-JIRA: automation failed in the periodic job
  web/cypress/e2e/regression/01.reg_alerts.cy.ts
  web/cypress/views/details-page.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#487 OCPBUGS-55455: feat: add alerting rules tab to dev console
  web/console-extensions.json
  web/src/components/alerting/AlertRulesDetailsPage.tsx
  web/src/components/alerting/AlertRulesPage.tsx
  web/src/components/hooks/usePerspective.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, qe-approved, ux-approved

#493 OCPBUGS-60199: feat: add alerting rules tab to dev console
  web/console-extensions.json
  web/src/components/alerting.tsx
  web/src/components/hooks/usePerspective.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, jira/severity-important, qe-approved, ux-approved

#497 NO-JIRA: improve consistency in tab string
  web/locales/en/plugin__monitoring-plugin.json
  web/src/components/alerting/AlertingPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#494 OCPBUGS-60198: fix legend height to avoid scroll overlap
  web/src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved, ux-approved

#500 OU-960: data-test injection on source code and UI automation refactoring
  web/cypress/downloads/openshift.csv
  web/cypress/e2e/02.coo_bvt.cy.ts
  web/cypress/e2e/coo/01.coo_bvt.cy.ts
  web/cypress/e2e/monitoring/01.bvt_monitoring.cy.ts
  web/cypress/e2e/monitoring/regression/01.reg_alerts.cy.ts
  web/cypress/support/commands.ts
  web/cypress/views/alerting-rule-details-page.ts
  web/cypress/views/alerting-rule-list-page.ts
  web/cypress/views/common.ts
  web/cypress/views/details-page.ts
  web/cypress/views/list-page.ts
  web/cypress/views/nav.ts
  web/cypress/views/silence-alert-page.ts
  web/cypress/views/silence-details-page.ts
  web/cypress/views/silences-list-page.ts
  web/package.json
  web/src/components/MetricsPage.tsx
  web/src/components/TypeaheadSelect.tsx
  web/src/components/alerting/AlertList/AggregateAlertTableRow.tsx
  web/src/components/alerting/AlertList/AlertTableRow.tsx
  web/src/components/alerting/AlertList/DownloadCSVButton.tsx
  web/src/components/alerting/AlertRulesDetailsPage.tsx
  web/src/components/alerting/AlertRulesPage.tsx
  web/src/components/alerting/AlertsDetailsPage.tsx
  web/src/components/alerting/SilenceForm.tsx
  web/src/components/alerting/SilencesDetailsPage.tsx
  web/src/components/alerting/SilencesPage.tsx
  web/src/components/alerting/SilencesUtils.tsx
  web/src/components/dashboards/legacy/legacy-dashboard.tsx
  web/src/components/dashboards/legacy/time-dropdowns.tsx
  web/src/components/data-test.ts
  web/src/components/kebab-dropdown.tsx
  web/src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#499 OU-848: Dependency update of dynamic plugin sdk and typescript
  web/.eslintrc.yml
  web/package-lock.json
  web/package.json
  web/src/actions/observe.ts
  web/src/components/TypeaheadSelect.tsx
  web/src/components/alerting/SilencesUtils.tsx
  web/src/components/console/console-shared/src/datetime/prometheus.ts
  web/src/components/console/utils/async.tsx
  web/src/components/console/utils/ref-width-hook.ts
  web/src/components/console/utils/single-typeahead-dropdown.tsx
  web/src/components/dashboards/legacy/useLegacyDashboards.ts
  web/src/components/hooks/useFeatures.ts
  web/tsconfig.json
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#507 NO-JIRA: README.md update
  README.md
Labels: jira/valid-reference, approved, qe-approved, ux-approved

#503 OU-932: automation - metrics
  web/cypress.config.ts
  web/cypress/downloads/openshift.csv
  web/cypress/e2e/monitoring/regression/02.reg_metrics.cy.ts
  web/cypress/fixtures/monitoring/constants.ts
  web/cypress/support/commands.ts
  web/cypress/support/index.ts
  web/cypress/views/alerting-rule-details-page.ts
  web/cypress/views/details-page.ts
  web/cypress/views/list-page.ts
  web/cypress/views/metrics.ts
  web/src/components/MetricsPage.tsx
  web/src/components/console/graphs/graph-empty.tsx
  web/src/components/data-test.ts
  web/src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#508 [release-4.18] NO-JIRA: update i18n strings
  web/console-extensions.json
  web/locales/en/plugin__monitoring-plugin.json
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#509 OBSINTA-776: Incident detection tests
  web/cypress/e2e/incidents/00.coo_incidents_e2e.cy.ts
  web/cypress/e2e/incidents/01.incidents.cy.ts
  web/cypress/fixtures/incidents/pod_crash_loop.yaml
  web/cypress/fixtures/incidents/prometheus_rule_pod_crash_loop.yaml
  web/cypress/support/commands.ts
  web/cypress/support/index.ts
  web/cypress/tsconfig.json
  web/cypress/views/incidents-page.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved
