Repository openshift/monitoring-plugin, pull requests merged in 2025-04, with the labels that each got.

#376 [release-4.18] OU-724: remove deleted image
  Dockerfile
  Dockerfile.dev
  Dockerfile.mcp
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#375 OU-724: remove dependency on deleted image
  Dockerfile.dev
  Dockerfile.mcp
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#374 OCPBUGS-54211: fix issue preventing dev silences from loading
  web/src/components/alerting.tsx
  web/src/components/alerting/AlertsDetailPage.tsx
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/hooks/useSilencesPoller.ts
  web/src/components/silence-form.tsx
Labels: lgtm, jira/valid-reference, approved, jira/valid-bug, qe-approved, ux-approved

#379 OU-678: fix: allow to set refresh interval to off
  web/src/components/console/utils/poll-hook.ts
  web/src/components/dashboards/legacy/useLegacyDashboards.ts
  web/src/components/query-browser.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#383 OU-702: re-add csv button for aggregated alert list
  web/src/components/alerting/AlertList/DownloadCSVButton.tsx
  web/src/components/alerting/AlertsPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#384 RHINENG-16773: fixed silence alerts data form not filled with alert details
  web/src/components/Incidents/IncidentsDetailsRowTable.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved

#391 OU-752: Clear out old queries when loading queries from URL
  web/src/components/metrics.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#389 OU-703: fix states filter in aggregated row
  web/src/components/alerting/AlertList/AggregateAlertTableRow.tsx
  web/src/components/alerting/AlertList/hooks/utils.ts
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#393 OU-757: Show cluster column heading on acm silences page
  web/src/components/alerting/SilencesPage.tsx
  web/src/components/alerting/SilencesUtils.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#392 OU-729,OU-723: Add label typeahead
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/alerting/SilencesPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#390 OU-760: Requests UX changes post PF-6
  web/src/components/alerting/AlertDetail/SilencedByTable.tsx
  web/src/components/alerting/SilencesUtils.tsx
  web/src/components/labels.tsx
  web/src/components/metrics.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#397 OCPBUGS-54292: Show column headings on metrics page
  web/src/components/metrics.tsx
Labels: lgtm, jira/severity-low, jira/valid-reference, approved, jira/valid-bug, qe-approved, ux-approved

#395 OU-750: update the metrics typeahead to look pf-6 native
  web/src/components/metrics/promql-expression-input.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#396 OU-767: Allow filtering by cluster name
  web/src/components/alerting/AlertsPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#399 OU-765: Don't break if cluster doesn't exist
  web/src/components/alerting/AlertsPage.tsx
  web/src/components/alerting/SilencesPage.tsx
Labels: lgtm, jira/valid-reference, approved, qe-approved, ux-approved

#394 OCPBUGS-48533: Reset variables when making orthongonal selections
  web/src/components/console/utils/single-typeahead-dropdown.tsx
  web/src/components/dashboards/shared/dashboard-dropdown.tsx
Labels: lgtm, jira/severity-moderate, jira/valid-reference, approved, jira/valid-bug, qe-approved, ux-approved

#398 NO-JIRA: fix(incidents): performance improvements for incidents page
  web/src/components/Incidents/AlertsChart/AlertsChart.jsx
  web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
  web/src/components/Incidents/IncidentsPage.jsx
Labels: lgtm, jira/valid-reference, approved, ok-to-test, qe-approved, ux-approved
